### ISSUE TITLE
Vue Storefront multistore checkout route name

### ISSUE THREAD

**Issue by ResuBaka** [Vendic/vsf-external-checkout#13]
We have currently the problem that the module is using storeCode-checkout as the name that is checked for. 

But the checkout name is always checkout and never prefixed with the storeCode. 

So can someone maybe explain me why it was done with storeCode-checkout check? 

When it is not needed anymore I could create a PR to remove it.

**Comment by jpetar** [comment]
I just read your issue and I think I had the same problem as you today and created the pull request right away.
https://github.com/Vendic/vsf-external-checkout/pull/14

**Comment by ResuBaka** [comment]
Nice and I have added comments which can improve the code some more.
