### ISSUE TITLE
Refactoring to new Vue Storefront v1.11+ and 2+

### ISSUE THREAD

**Issue by cewald** [Vendic/vsf-external-checkout#16]
Hi, we have refactored this VSF module for the new VSF 1.11.+ version.
Are you interested in this update? Or – How can we contribute?

**Comment by Tjitse-E** [comment]
Hi @cewald! Sure, just create a pull request.

**Comment by Tjitse-E** [comment]
PR [Merged and released](https://github.com/Vendic/vsf-external-checkout/releases/tag/3.0.0)
