### ISSUE TITLE
Execute `cart/sync` (1.11) or `cart/serverPull` (1.10) before redirect

### ISSUE THREAD

**Issue by pkarw** [Vendic/vsf-external-checkout#19]
Please do modify the [`beforeEach.ts`](https://github.com/Vendic/vsf-external-checkout/blob/baeefd179038b2bd9b4a1a00c95b82b131b61b65/router/beforeEach.ts#L14) in order to make sure the sync process has been fully executed BEFORE redirecting the user to Magento checkout.

Suggested change:

```js
export function beforeEach(to: Route, from: Route, next) {
  const cartToken: string = rootStore.state.cart.cartServerToken;
  const userToken: string = rootStore.state.user.token;
  const externalCheckoutConfig = {...config.externalCheckout};
  const cmsUrl: string = externalCheckoutConfig.cmsUrl;
  const stores = externalCheckoutConfig.stores;
  const storeCode = currentStoreView().storeCode
  const multistoreEnabled: boolean = config.storeViews.multistore

  if (multistoreEnabled) {
    **await rootStore.dispatch('cart/sync')**
    if (storeCode in stores && to.name === storeCode + '-checkout') {
      window.location.replace(stores[storeCode].cmsUrl + '/vue/cart/sync/token/' + userToken + '/cart/' + cartToken)
    } else if (storeCode in stores && to.name === 'checkout' && stores[storeCode].cmsUrl !== undefined) {
      window.location.replace(stores[storeCode].cmsUrl + '/vue/cart/sync/token/' + userToken + '/cart/' + cartToken)
    } else {
      next()
    }
  } else {
    if (to.name === 'checkout') {
      window.location.replace(cmsUrl + '/vue/cart/sync/token/' + userToken + '/cart/' + cartToken)
    } else {
      next()
    }
  }
}

```

Otherwise there could be a situation when the sync hasn't been fully executed and user getting to the Magento checkout sees some discrepancies between Magento and Vue Storefront carts. For example - product added to the VSF cart hasn't been yet added to Magento cart.

The action to be called:
- `cart/sync` for 1.11
- `cart/serverPull` for 1.10

**Comment by pkarw** [comment]
@Tjitse-E I just wanted to follow up on this issue. Any chances to get it fixed?:)

**Comment by Tjitse-E** [comment]
@pkarw I really don't have time for this at the moment. I've added the 'help wanted' label, hopefully someone else can prepare a PR!

**Comment by RakowskiPrzemyslaw** [comment]
Hi, here is PR that should solve the problem for version 3.0.0: https://github.com/Vendic/vsf-external-checkout/pull/24
